# 빌드 스테이지
ARG NODE_VERSION=20.13.1
FROM node:${NODE_VERSION} AS builder

WORKDIR /build
COPY package*.json ./
RUN npm ci --no-audit
COPY . .
RUN npm run build

# 실행 스테이지
FROM node:${NODE_VERSION}

WORKDIR /app
COPY --from=builder /build/package-lock.json ./
COPY --from=builder /build/package.json ./
COPY --from=builder /build/dist ./dist
COPY --from=builder /build/node_modules ./node_modules

# 포트 개방 (NestJS 기본 포트)
EXPOSE 3000

# 컨테이너가 실행될 때 실행할 명령어
CMD ["npm", "run", "start:prod"]